/*CRIANDO UM NOVO PERFIL*/
CREATE ROLE novoPerfil;

/*CRIANDO UM NOVO USUARIO E O ADICINANDO AO PERFIL CRIADO ANTERIORMENTE*/
CREATE USER luiz IDENTIFIED BY 'senhaBemForte' DEFAULT ROLE novoPerfil;

/*DEFININDO O USUARIO CRIADO PARA APENAS PODER UTILIZAR O COMANDO SELECT*/
GRANT SELECT ON comabem.* TO luiz;

/*AGORA TENTAR FAZER UMA INSERÇÃO DE DADOS, APRESENTARA O ERRO PORQUE O USUARIO ESTA LIBERADO APENAS PARA SELECT*/
INSERT INTO Produtos(ds_produto, vl_produto, qt_produto, cd_unidade) VALUES ("Bolo de Cenoura", 20.00, 3, 2);